# -*- coding: utf-8 -*-
"""ds200.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10hbSxPE3SCxoGPg4Zt95DwMXgkH7cpv2

## DS200 Research Method Module 4:

Datasets used: State level Literacy rate in % from 1951-2011 and Gender based Literacy rate in % from 1951-2011 <br>
(https://data.gov.in/catalog/literacy-rate?filters%5Bfield_catalog_reference%5D=135639&format=json&offset=0&limit=6&sort%5Bcreated%5D=desc)
"""

## Importing Libraries
import matplotlib.pyplot as plt
import numpy as np
import json
from collections import defaultdict
import csv
import pandas as pd

state = pd.read_csv('datasets/State_level_lit_rate.csv')
gender = pd.read_csv('datasets/Gender_based_lit_rate.csv')

state

gender

"""## Data analysis of Gender based literacy rate

### Bar Plot
"""

# set width of bar 
barWidth = 0.25
fig,ax = plt.subplots(figsize=(18,7))

# set height of bar 
total = gender.iloc[0].values[1:]
male = gender.iloc[1].values[1:]
female = gender.iloc[2].values[1:]

# Set position of bar on X axis 
br1 = np.arange(len(total)) 
br2 = [x + barWidth for x in br1] 
br3 = [x + barWidth for x in br2] 

def autolabel(rects):
    """Attach a text label above each bar in *rects*, displaying its height."""
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{}'.format(height),
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')
        
# Make the plot 
rect = ax.bar(br1, total, width = barWidth, edgecolor ='grey', label ='Total') 
autolabel(rect)
rect = ax.bar(br2, male, width = barWidth, edgecolor ='grey', label ='Male') 
autolabel(rect)
rect = ax.bar(br3, female, width = barWidth, edgecolor ='grey', label ='Female') 
autolabel(rect)

# Adding Xticks 
plt.xlabel('Literacy rate',fontsize=15)
plt.ylabel('Year',fontsize=15) 
plt.xticks([r + barWidth for r in range(len(total))], gender.columns[1:])
plt.legend()
plt.title('Variation of literacy rate over the years',fontsize=20)
plt.savefig('Bar_plot.png')
plt.show()

"""#### Observation:
From the above plot, we observe a continuous increase in literacy rate over the years for both the genders. Also, the gap between male and female literacy rate can be seen to be decreasing. For a developing country like India, this plot shows a positive ray of hope towards achieving greater literacy rate with time.

### Scatter Plot
"""

fig = plt.figure(figsize=(8,7))
plt.scatter(gender.iloc[0].values[1:], gender.iloc[1].values[1:]/gender.iloc[2].values[1:])
plt.xlabel('Total literacy rate over the years',fontsize=13)
plt.ylabel('Male to Female literacy ratio',fontsize=13)
plt.title('Literacy rate ratio with increasing literacy',fontsize=20)
plt.grid()
plt.savefig('Scatter_plot.png')
plt.show()

"""#### Observation:
From the above plot, we observe as the total literacy increases over the years, the ratio of male to female literacy rate decreases. There exists a negative linear correlation between total literacy and gender literacy variation. As more people are educated, more females are encouraged to be literate. This helps in bridging the gap among gender literacies. This is a good sign indicating towards removal of societal discrepancies over time.

## Data analysis of State level literacy rate
### Box Plot
"""

f = open('datasets/literacy.json', 'r')
data = f.read()
x = json.loads(data)
# keys = ['1951','1961','1971','1981','1991','2001','2011']
col = state.columns[1:]
data = defaultdict(list)
for t in x['data']:
    for id in range(-(len(col)), 0):
        k = col[id]
        if t[id] != 'NA':
            d = float(t[id])
        data[k].append(d)

box_data=[]
labels = []
for key, value in data.items():
    box_data.append(value)
    labels.append(key)

fig,ax = plt.subplots(figsize=(10,6))
bp = ax.boxplot(box_data, labels=labels, patch_artist=True)
plt.title('Literacy rate across different states in India',fontsize=20)
plt.xlabel('Year',fontsize=15)
plt.ylabel('Literacy rate',fontsize=15) 

# fill with colors
colors = ['pink', 'lightblue', 'lightgreen', 'yellow', 'gray', 'olive', 'brown']
for bplot in (bp):
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)

plt.grid()
plt.savefig('Box_plot.png')
plt.show()

"""#### Observation:
From the above plot, we observe that the median literacy rate almost increases over years and there exists a reduction in variance between literacy rate of all states. With increasing time, this trend is again promising to remove literacy variation over the country.
"""

